alias python="python3"
alias pip="pip3"
alias c="cd"
alias vi="vim"
alias pdf="xdg-open"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
